
version: '3'

services:
  backend:
    build:
      context: ./blog_backend
      args:
        DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost, api}
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-secret}
        CORS_ORIGIN_WHITELIST: ${CORS_ORIGIN_WHITELIST:-*, }
        ENV: ${ENV:-dev}
    command: gunicorn blog_backend.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000
  frontend:
    build:
      context: ./blog_frontend
      args:
        API_URL:  ${API_URL:-http://localhost}
    ports:
      - 80:8080
    depends_on:
      - backend
