apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    role: testbed_backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      role: testbed_backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: testbed_backend
    spec:
      containers:
        - name: backend
          image: entigoandrke/testbed_backend:v0.01
          args:
            - gunicorn
            - blog_backend.wsgi
            - --bind
            - 0.0.0.0:8000
            - --log-level
            - debug
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_ALLOWED_HOSTS
              value: backend, 127.0.0.1, *
            - name: DJANGO_SECRET_KEY
              value: 162(hbn1v^yzi-srdiw8cpf1txnf@6vxw8*17ofowjpt28_9qd4c16
            - name: DJANGO_CORS_ORIGIN_WHITELIST
              value: frontend, api, *

          resources: {}
      restartPolicy: Always
status: {}
