apiVersion: v1
kind: Service
metadata:
  labels:
    role: testbed_backend
  name: backend
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    role: testbed_backend
  sessionAffinity: ClientIP
status:
  loadBalancer: {}
