apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: testbed_frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      role: testbed_frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: testbed_frontend
    spec:
      containers:
        - name: frontend
          image: entigoandrke/testbed_frontend:v0.01
          ports:
            - containerPort: 8080
          env:
            - name: API_URL
              value: "http://backend:8000"
            - name: API_HOST
              value: "backend"
            - name: API_HOST_PORT
              value: "8000"
            - name: NGINX_LISTEN_PORT
              value: "8080"
          resources: {}
      restartPolicy: Always
status: {}
