apiVersion: v1
kind: Service
metadata:
  labels:
    role: testbed_frontend
  name: frontend
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    role: testbed_frontend
  sessionAffinity: ClientIP
status:
  loadBalancer: {}
